# -*- mode: ruby -*-
# vi: set ft=ruby :

# Specify Vagrant version and Vagrant API version
Vagrant.require_version ">= 2.0"
VAGRANTFILE_API_VERSION = "2"

# Create and configure the Docker container(s)
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  ###
  # Development box.
  #
  config.vm.define "server-local" do |node|
    node.vm.box = "ubuntu/focal64"
    node.vm.hostname = "server-local"
    node.vm.network "private_network", ip: "172.16.3.3"
    node.vm.network "forwarded_port", guest: 80, host: 8080
    node.vm.synced_folder "../frontend/build", "/vagrant/html"
    node.vm.provision :shell, path: "./setup/install-env.sh"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
    end
  end
end
